### ISSUE TITLE
Create database error

### ISSUE THREAD

**Issue by ZHumphries** [sundy-li/burrowx#10]
If authentication & authorisation is enabled in influxdb and the user doesn't have admin rights, burrowx throws the following error.

panic: error authorizing query: burrowx not authorized to execute statement 'CREATE DATABASE burrowx', requires admin privilage

This occurs even when the database already exists.

**Comment by ZHumphries** [comment]
Hi Sundy,

Any chance this will be fixed anytime soon, no pressure, I just need to know if I should look into alternatives?

Cheers
Zak

**Comment by sundy-li** [comment]
@ZHumphries  sorry for the delay
I think the influxdb database `burrowx` should be created manually.

So try the latest code or releaser I just pushed. Thank you.
