### ISSUE TITLE
burrowx doesn't find consumer after upgrading to kafka 2.0

### ISSUE THREAD

**Issue by asyd** [sundy-li/burrowx#13]
Hello folks,

after upgrading a kafka cluster from 0.11.x to 2.0.1 and burrowx as well, burrowx is not able to find any consumer.

When I start burrowx with loglevel set to `debug`, I have the following message:

```
Topic xxx not found any consumer
```

However, when I run:

```
./bin/kafka-consumer-groups.sh --bootstrap-server xx:9092,[..] --topic xxx -describe
TOPIC                  PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
xxxx                   3          317717          317717          0               rdkafka-8c07adcf-77ef-40d9-9cc8-38312834f168 /xxx.xxx.xxx.xx rdkafka
```

As you can see, the output is good. Note I have few others kafka monitoring tool, like datadog and Kafka Yahoo Manager, and they still work fine.

Any idea by chance?

**Comment by sundy-li** [comment]
Confirmed, it had some problem on kafka 2.0

**Comment by sundy-li** [comment]
#12 This pr may solve this problem, could u have a try?

**Comment by asyd** [comment]
Sounds like I still have the issue.

Here what I done:

```
git clone git@github.com:sundy-li/burrowx.git
git checkout origin/feature/partition_metric
go build
./burrowx -config config/burrowx.json
```

Still having `Topic xxx not bound any consumer`

**Comment by sundy-li** [comment]
hmm, seems you are still using old version burrowx

**Comment by asyd** [comment]
Indeed, I renamed `~/go` to ~/go.old` and retry to run `go build` but it failed. I must confess I'm not very aware of golang building

**Comment by asyd** [comment]
Ah, got it! 

And it's now working!

**Comment by sundy-li** [comment]
Nice, I will merge this branch and release a new version.

**Comment by sundy-li** [comment]
@asyd  I fixed a bug and Released v2.0

https://github.com/sundy-li/burrowx/releases

**Comment by asyd** [comment]
Thanks you! Is the bug you found relative to log size by chance?

**Comment by sundy-li** [comment]
Yes, the bug is that the log size may be decreased by chance.

Because the `partition` column should be the `tags` either than `fields` in Influxdb.
