### ISSUE TITLE
Can not catch data from Kafka server when the servers are busy

### ISSUE THREAD

**Issue by Yin-Zhang-TR** [sundy-li/burrowx#3]
As we use burrowx to monitor the lags of our kafka cluster, it is so amazing to catch data and put them into influxdb. But sometimes, it can not get any data to some consumers(not all of them, just a part of them).
So there are some blank period when we check the information with grafana.

So could you help to check what happened?
Thanks.

**Comment by sundy-li** [comment]
Hmm,  it's possible to happen

1.  May be your kafka cluster machines are in high load. So they went busy to handle the request.

2.  I suggest you to just monitor the topics and the consumers by your need, that will reduce the pressure of kafka offset fetcher. If your kafka cluster has m topics, each topic has p partitions, and each topic has c consumers,  it may  be at most    `O(m  * p * c)`  requests  in the fetch duration(default to 5 seconds).

You could use  the `groupBlacklist ` and the `topicFilter ` config to make that.

**Comment by dalenavi** [comment]
+1, this issue makes this excellent project unusable.

**Comment by sundy-li** [comment]
Fixed at #12 ,  no longer use `__consumer_offsets` any more.
