### ISSUE TITLE
Service dies if a broker is unreachable

### ISSUE THREAD

**Issue by cptcanuck** [sundy-li/burrowx#9]
We have 4 clusters I'm monitoring, but one of them has/had a config issue, meaning BurrowX can connect to the cluster, but when the consumer is redirected to the proper broker (the leader for the _consumer_group partition with the data) it can't reach the broker any longer.  BurrowX will run for a little while like this, polling the other clusters happily, and failing on the bad cluster, then eventually it will just die:

```
2018-08-29 13:54:44 [DEBUG] setting log.textnow.backend.amsimport:logstash-amsimport_service:1 offset:21883
panic: dial tcp 1.2.3.4:9092: i/o timeout

goroutine 1 [running]:
github.com/sundy-li/burrowx/monitor.(*KafkaClient).Start(0xc42013a380)
	/go/src/github.com/sundy-li/burrowx/monitor/client.go:173 +0x6be
github.com/sundy-li/burrowx/monitor.(*Fetcher).Start(0xc420122c40)
	/go/src/github.com/sundy-li/burrowx/monitor/fetcher.go:29 +0x4a
main.main()
	/go/src/github.com/sundy-li/burrowx/main.go:34 +0x15b
```

It would be nice if it would just keep running and erroring, vs dying.  Granted, this helped me find the config problem with my cluster, but it's taken a bunch of fiddling around to get there :)

**Comment by sundy-li** [comment]
Hi, I still think it would be better to panic this error. Because this tools is completely depend on kafka consumer.

**Comment by cptcanuck** [comment]
But if you have multiple Kafka clusters it would be ideal to keep
monitoring the others, even if one has a problem.  I suppose I could move
to deploying a monitoring container per cluster but I'd rather run one
instance that monitors each cluster.

For bonus points, you could emit a “healthy” and “unhealthy” metric to
influx so that if one cluster stops being monitored you could alert on it,
as a way to manage hidden failures.

**Comment by sundy-li** [comment]
@cptcanuck  I misunderstood your meanings, you are right. I just fix it.
You could download the binary files from  [release](https://github.com/sundy-li/burrowx/releases) now.

Sorry for the delay, really busy for other things.
